---
language: perl
install:
  - sudo apt-get update
  - sudo apt-get --no-install-recommends install devscripts python ruby php5-cli gawk pylint
  - sudo apt-get --no-install-recommends install pkg-config libdb-dev libvirt-dev libexpat-dev

  # Modules used by test script
  - cpanm --notest Capture::Tiny
  - cpanm --notest File::Find
  - cpanm --notest Test::More
  #
  # Modules used by plugins
  - cpanm --notest Asterisk::AMI
  - cpanm --notest BerkeleyDB
  - cpanm --notest Cache::Memcached
  - cpanm --notest DBD::Pg
  - cpanm --notest Data::Dump
  - cpanm --notest Date::Manip
  - cpanm --notest Date::Parse
  - cpanm --notest Device::SerialPort
  - cpanm --notest FCGI::Client
  - cpanm --notest File::ReadBackwards
  - cpanm --notest File::Tail::Multi
  - cpanm --notest Graphics::ColorObject
  - cpanm --notest IPC::Run3
  - cpanm --notest IPC::ShareLite
  - cpanm --notest JSON::Any
  - cpanm --notest Mail::Sendmail
  - cpanm --notest Modern::Perl
  - cpanm --notest MooseX::POE
  - cpanm --notest Net::DNS
  - cpanm --notest Net::OpenSSH
  - cpanm --notest Net::SNMP
  - cpanm --notest Net::Telnet
  - cpanm --notest Net::Telnet::Cisco
  - cpanm --notest POE
  - cpanm --notest POE::Component::IRC
  - cpanm --notest POE::Quickie
  - cpanm --notest Proc::ProcessTable
  - cpanm --notest Redis
  - cpanm --notest WWW::Mechanize::TreeBuilder
  - cpanm --notest Text::Iconv
  - cpanm --notest XML::LibXML
  - cpanm --notest XML::Simple
  - cpanm --notest XML::Twig
  - cpanm --notest nvidia::ml
  # - Sys::Virt version matching the test system's libvirt-dev
  - cpanm --notest DANBERR/Sys-Virt-0.9.8.tar.gz
  # Modules used by plugins, but missing on cpan
  # - Sun::Solaris::Kstat
  # - VMware::VIRuntime
  # - MythTV
script: "prove"
