---
language: perl
install:
  - sudo apt-get update
  - sudo apt-get --no-install-recommends install devscripts python ruby php5-cli gawk
  #
  # Modules used by test script
  - cpanm --notest Test::More File::Find Capture::Tiny
  #
  # Modules used by plugins
  - cpanm --notest Asterisk::AMI Cache::Memcached BerkeleyDB DBD::Pg Data::Dump Device::SerialPort FCGI::Client File::ReadBackwards File::Tail::Multi Graphics::ColorNames IPC::Run3 IPC::ShareLite Modern::Perl MooseX::POE Net::Telnet Net::Telnet::Cisco POE Proc::ProcessTable Redis Sys::Virt WWW::Mechanize::TreeBuilder nvidia::ml
  # Modules used by plugins, but missing on cpan
  # - Sun::Solaris::Kstat
  # - VMware::VIRuntime
  # - MythTV
script: "prove"
